### ISSUE TITLE
How can I get "admin" command?

### ISSUE THREAD

**Issue by MasaGon** [simov/express-admin-examples#5]
Could you tell me how I can get "admin" command to start express-admin-examples?
Any reference document is also appreciated.

**Comment by simov** [comment]
@MasaGon just run this command in your terminal

``` bash
npm install -g express-admin
```

Here is the [official documentation](http://simov.github.io/express-admin/) with everything you should know about Express Admin. You may also want to look at the [screencast](http://www.youtube.com/watch?v=1CdoCB96QNk)

**Comment by MasaGon** [comment]
Hello @simov ,

I've installed express-admin locally and use "./node_modules/express-admin/bin/admin" instead.It worked well.

Thanks a lot!
