### ISSUE TITLE
Could not find `pg` or `pg.js` module

### ISSUE THREAD

**Issue by carlosfaria94** [simov/express-admin-examples#8]
Hi,

When I do:

`admin config/pg/`

It's returned:

> Could not find `pg` or `pg.js` module

Any idea what might be?

**Comment by simov** [comment]
You have to install it manually:

``` bash
$ npm install pg
```

`pg.js` is obsolete.

**Comment by carlosfaria94** [comment]
Yeah of course, I made it, but didn't work. Now I installed it globally (-g) and works.

I got another problem
`admin config/pg/`

Returned 

> Empty schema!

Thanks!

**Comment by simov** [comment]
Yep, global would do it, or anywhere up in the directory tree where the admin can find it.

You need a schema with some tables in it. Express Admin is about editing records in existing tables, so a database with no tables is pointless in this case.

**Comment by carlosfaria94** [comment]
Yeah right, I realized that the import of SQL files failed.

Thanks @simov ! Great module!
